### ISSUE TITLE
Define a syncronization workflow

### ISSUE THREAD

**Issue by aoloe** [scribusproject/scribus-old-to-be-deleted#13]
Currently, we have:

- The "svn" branch that get's automtically updated from the scribus' svn server.
- The "master" branch that is manually kept in sync with the "svn" branch. This branch is where pull requests from the forks will be committed to 'master' after review.

We need to find a good workflow that allows us to keep the "master" in sync with the commits with the team.

The issues that should be considered:
- conflicts that happen when a patch from "master" is also applied -- with small changes -- into the svn "trunk".
- each patch that gets into "master" (on github) will have also to be manually uploaded to the bug tracker and we will have to wait (potentially for a long time) before they are applied "upstream".

As long as we have not pulled anything into master yet, we can use the simple workflow described by sarath:

Until we have a good workflow we can follow a simpler one (made possible by the fact that "master" has no changes yet):
- https://github.com/sarathms/scribus/wiki/git-developer-workflow describes how anybody can make a pull request for the update.
- here is the workflow for somebody having push rights on the scribusproject repository:

  ```
  $ git clone git@github.com:scribusproject/scribus.git scribus-github
  $ git checkout svn
  $ git pull
  $ git checkout master
  $ git pull
  $ git merge svn -X theirs
  $ git push origin master
```

**Comment by luzpaz** [comment]
Because we haven't heard from @moskalenko I've for the time being disassociated @mrscribe from the project and @aoloe I anticipate will be working on implementing @chhitz's great work at https://github.com/scribusproject/scribus_svn_git

**Comment by luzpaz** [comment]
This issue was moved to scribusproject/scribus#8
