### ISSUE TITLE
port the scripter to python3 and pyqt5

### ISSUE THREAD

**Issue by aoloe** [scribusproject/scribus-old-to-be-deleted#4]
the new scripter is compiling again, but crashes on boot.

the reason is probably that it has to be ported to pyqt5 (and then also to python3) to be compatible with scribus' move to qt5.

i have created a scripter branch and i propose that we discuss implementation details and issues in this ticket / issue tracker.

**Comment by luzpaz** [comment]
This issue was moved to scribusproject/scribus#2
